---
title: "Predict the damage to a building"
author: "Mohammed Ali"
date: "July 3, 2018"
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DataExplorer)
library(formattable)
library(knitr)
```

```{r}
train <- as_tibble(read.csv("data/train.csv"))
#building_structure <- as_tibble(read.csv("data/Building_Structure.csv"))
#building_ownership <- as_tibble(read.csv("data/Building_Ownership_Use.csv"))

train$has_geotechnical_risk <- as.factor(train$has_geotechnical_risk)
train$has_geotechnical_risk_fault_crack <- as.factor(train$has_geotechnical_risk_fault_crack)
train$has_geotechnical_risk_flood <- as.factor(train$has_geotechnical_risk_flood)
train$has_geotechnical_risk_land_settlement <- as.factor(train$has_geotechnical_risk_land_settlement)
train$has_geotechnical_risk_landslide <- as.factor(train$has_geotechnical_risk_landslide)
train$has_geotechnical_risk_liquefaction <- as.factor(train$has_geotechnical_risk_liquefaction)
train$has_geotechnical_risk_other <- as.factor(train$has_geotechnical_risk_other)
train$has_geotechnical_risk_rock_fall <- as.factor(train$has_geotechnical_risk_rock_fall)
train$has_repair_started <- as.factor(train$has_repair_started)
```

# Data Profiling Report
## Basic Statistics
```{r Basic_Statistics, results = 'asis'}
kable(gather(introduce(train), Name, Value))
```
